name: reservoir
description: An indexed table-like data type that works well with Hive boxes.
version: 4.0.1
homepage: https://github.com/moontreeapp/reservoir

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.3
  hive: ^2.0.4
  ordered_set: ^3.1.0
  rxdart: ^0.27.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
